// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gggxbqvrcdvptfjyyqca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnZ3hicXZyY2R2cHRmanl5cWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTg3MTQsImV4cCI6MjA3NDIzNDcxNH0.y4og_9cedlGPYQTDd6rbQiXrZmg1ihGfG2EfgUFWKYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});